apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vtexio-grafana-plugin
  annotations:
    github.com/project-slug: vtex/vtexio-grafana-plugin
    vtex.com/platform-flow-id: CommDev#3,VTEXEng#1
spec:
  type: other
  lifecycle: unknown
  owner: te-0029
